language: generic
cache: ccache

matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      env:
        - LLVM_HINT="/usr/local/opt/llvm"
        - LLVM_VERSION="4.0.0"
    - os: linux
      sudo: required
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
      env:
        - LLVM_HINT="/usr/local/opt/llvm" CXX=g++-5 CC=gcc-5
        - LLVM_VERSION="4.0.0"

before_install:
  - ./.travis/dependencies.sh

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -DLLVM_HINT=$LLVM_HINT
  - make
  - cd test
  - ctest
