language: cpp
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
matrix:
  include:
    - os: osx
      osx_image: xcode7.3
    - os: linux
      dist: trusty
      sudo: required
  exclude:
    - os: osx
      compiler: gcc
before_install:
  - ./.travis/dependencies.sh
script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug
  - make
  - cd test
  - ctest
