language: cpp
os:
  - osx
osx_image: xcode7.3	
before_install:
  - brew update
  - brew instal libxml2
  - brew instal llvm
script:
  - mkdir build
  - cd build
  - cmake .. && make
  - cd test
  - ctest
